### ISSUE TITLE
server not responding 

### ISSUE THREAD

**Issue by lafayatte** [mtobeiyf/sketch-to-art#13]
`Access to XMLHttpRequest at 'http://localhost:5001/' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by mtobeiyf** [comment]
You need to use `CORS`. It's been enabled by default in the latest code.

https://github.com/mtobeiyf/sketch-to-art/blob/db4c38129de04a280255f53fea54825cf1fb9ce2/server/app_pix.py#L19-L22
