### ISSUE TITLE
How Can The Backend Runs So Fast?

### ISSUE THREAD

**Issue by S-HuaBomb** [mtobeiyf/sketch-to-art#14]
I am now learning Pytorch, so I want to implement the WCT tranfer backend in Pytorch, and I I refer to this project: [PytorchWCT](https://github.com/sunshineatnoon/PytorchWCT). I run it successfully in my labtop too, but it takes about 120 seconds at a time, I don't have a cuda GPU, I run both sketch-to-art and this PytorchWCT on My CPU. According to his tutorial, I downloaded the Pretrained encoder and decoder model:
![image](https://user-images.githubusercontent.com/39048551/81530168-e97ccd00-9392-11ea-8571-e16f49db02f9.png)
and successfully load and ran well, but just too slow compared with yours which takes less than 20 seconds each time. So how can your backend run so fast, what can I do in Pytorch?

**Comment by mtobeiyf** [comment]
I suggest you took a look at their model implementations and inference code. 
Seems the PyTorch version uses more VGG model during the inference stage.

**Comment by S-HuaBomb** [comment]
> I suggest you took a look at their model implementations and inference code.
> Seems the PyTorch version uses more VGG model during the inference stage.

I don't know where is the problem, don't you use five codecs in the backend?

In the PytorchWCT:
[WCT.py](https://github.com/sunshineatnoon/PytorchWCT/blob/master/WCT.py):
![image](https://user-images.githubusercontent.com/39048551/81580757-6e420800-93e0-11ea-842f-451357d16149.png)

[util.py](https://github.com/sunshineatnoon/PytorchWCT/blob/master/util.py):
![image](https://user-images.githubusercontent.com/39048551/81580945-a8aba500-93e0-11ea-857a-f257d420dcc6.png)

if you would like to running the PytorchWCT in windows or Pytorch 1.3+, here [MyPytorchWCT](https://github.com/S-HuaBomb/PytorchWCT) I made some changes to make the project run on windows and python1.3+.

**Comment by mtobeiyf** [comment]
I don't know the exact reasons why his implementation is slower. 
The implementation in my repo is ported from [https://github.com/eridgd/WCT-TF](https://github.com/eridgd/WCT-TF). 
Please take more look at the source code, since all the model implementations are clear there. And you could compare the differences accordingly.

**Comment by S-HuaBomb** [comment]
OK, Thx
