### ISSUE TITLE
Server not responding

### ISSUE THREAD

**Issue by Liameternal** [mtobeiyf/sketch-to-art#2]
II do as your guider, but it occurs this problem"Server not responding, check your Internet connection first. You can view details in the About page. To experience the app, please contact the author for help.", how can i solve it?

**Comment by mtobeiyf** [comment]
First, make sure you could run the backend server. 
For example, `python app_stylize.py`, and it will listen to the localhost port.

Uncomment this line `# CORS(app)` in both `app_pix.py` and `app_stylize.py` to allow CORS
Then, rerun the two scripts separately
https://github.com/mtobeiyf/sketch-to-art/blob/master/server/app_pix.py#L22

You could also use `F12` in your browser to check the console output of the frontend webpage and see if the backend service is working.
Good luck

**Comment by Liameternal** [comment]
Thank you for your reply, but there still have some problems, 
OSError: File models/pix2pix/export.meta does not exist.
![image](https://user-images.githubusercontent.com/25942745/54658640-6bfc5a80-4b09-11e9-9821-65798534ca3a.png)

**Comment by mtobeiyf** [comment]
The pretrained pix2pix model is here: https://github.com/mtobeiyf/sketch-to-art/releases
Please download and put it in the corresponding directory.
And other models could be downloaded via the scripts provided under the models directory.

**Comment by Liameternal** [comment]
ah...Maybe it does work, 
![image](https://user-images.githubusercontent.com/25942745/54660164-3870fe80-4b10-11e9-9056-2fb87b7ae872.png)
What's the problem?

**Comment by mtobeiyf** [comment]
Have you run the `app_stylize.py` script?
And you have to make sure the models are placed under the `./models` folder
See https://github.com/mtobeiyf/sketch-to-art/blob/master/server/README.md and
https://github.com/mtobeiyf/sketch-to-art/blob/master/server/models/download_models.sh

**Comment by Liameternal** [comment]
I tyied, but i always got this issue, "ImportError: cannot import name 'preserve_colors_np' from 'utils' (E:\Workspace\VirtualEnv\sketch-to-art\lib\site-packages\utils\__init__.py)", I can't find a way to solve it on the web...

**Comment by mtobeiyf** [comment]
Please go to the server root by `$cd server` and run `$ python app_stylize.py`
not ~~`$ python server/app_stylize.py`~~
