### ISSUE TITLE
What dataset you use for pix2pix?

### ISSUE THREAD

**Issue by lognat0704** [mtobeiyf/sketch-to-art#28]
Hi Fing,

Thanks for your excellent work. I have question about the model of pix2pix. Could you tell me what dataset you used to train the pix2pix model? 

Best,
Nelson

**Comment by mtobeiyf** [comment]
See page 4
https://github.com/mtobeiyf/sketch-to-art/files/2112403/Artistic_Image_Generation_from_Sketch.pdf
