### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by purse1996** [mtobeiyf/sketch-to-art#5]
富神：
我在跑app_stylize时候报错
  File "./wct\wct.py", line 34, in __init__
    ss_patch_size=self.ss_patch_size, ss_stride=self.ss_stride)
  File "./wct\model.py", line 62, in __init__
    self.vgg_model = vgg_from_t7(vgg_path, target_layer=deepest_target)
  File "./wct\vgg_normalised.py", line 38, in vgg_from_t7
    trainable=False)(x)
  File "E:\Anaconda3\envs\livedemo\lib\site-packages\keras\engine\base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "E:\Anaconda3\envs\livedemo\lib\site-packages\keras\layers\convolutional.py", line 141, in build
    constraint=self.kernel_constraint)
  File "E:\Anaconda3\envs\livedemo\lib\site-packages\keras\engine\base_layer.py", line 279, in add_weight
    weight = K.variable(initializer(shape, dtype=dtype),
TypeError: <lambda>() got an unexpected keyword argument 'dtype'
是keras的版本不对吗

**Comment by mtobeiyf** [comment]
改一下 `server\wct\vgg_normalised.py` 35-38行

```
x = Conv2D(filters, kernel_size, padding='valid', activation=None, name=name,
            kernel_initializer=lambda shape, dtype: K.constant(weight, shape=shape, dtype='float32'),
            bias_initializer=lambda shape, dtype: K.constant(bias, shape=shape, dtype='float32'),
            trainable=False)(x)
```

**Comment by purse1996** [comment]
富神 你那还有以前pix2pix的训练好的model吗  做一个公选课的展示demo 实在不想再重新训练了




张帅宾

Fing <notifications@github.com> 于2019年10月17日周四 上午2:29写道：

**Comment by mtobeiyf** [comment]
更新了一下 repo 
这个脚本可以下载模型 [download_models.sh](https://github.com/mtobeiyf/sketch-to-art/blob/master/server/models/download_models.sh)
这个能直接运行 [run.sh](https://github.com/mtobeiyf/sketch-to-art/blob/master/run.sh)
Python 的 [requirements.txt](https://github.com/mtobeiyf/sketch-to-art/blob/master/server/requirements.txt)

Windows 的话手动下载运行就行~

**Comment by mtobeiyf** [comment]
也可以用 docker 直接运行整个 application
https://github.com/mtobeiyf/sketch-to-art#run-with-docker

**Comment by purse1996** [comment]
嗯嗯 富神可以了 给富神打call 哈哈

Fing <notifications@github.com> 于2019年10月17日周四 下午2:24写道：
