### ISSUE TITLE
数据集问题以及模型训练问题

### ISSUE THREAD

**Issue by Chungegeya** [mtobeiyf/sketch-to-art#50]
fing神您好：
     很感谢您这个项目开源，我对这个AI作画方向很感兴趣准备研究这个，您的论文和开源给了我很大帮助。然后我有一些问题可能需要您的指导（鼠鼠是初学者）。
     1、看您论文这数据集是CUHKPQ选取风景画，然后边缘提取，得到对应的草图，形成数据集。但是我看了下结果应该是黑底线条是白色的，同时杂乱的线条也比较多，您是如何去掉的，要怎么调整？有源代码提供嘛？希望您能指导下，然后我希望的是您是否方便直接提供您的数据集（鼠鼠羞耻且过分的请求）。
     2、如果输入的草图中有多个物体轮廓，比如说有山有水有亭台楼阁，还能生成嘛？
     希望能得到fing神的帮助，祝您工作顺利，身体健康！

**Comment by imfing** [comment]
1. 如果你觉得杂乱线条比较多的话不妨边缘提取之后再做一下[erosion](https://homepages.inf.ed.ac.uk/rbf/HIPR2/erode.htm)，或者你再看看HED算法有没有什么参数（例如 阈值）可以调整输出结果。源代码可能我也找不到了 🤦 and 数据集
2. 这个理论上应该也是可以的，不过可能效果不是很好，取决于 1）你的训练集 2）输入的草图的质量，理论上输入草图越接近边缘提取后的图，能够得到更好的输出图片

**Comment by imfing** [comment]
此外还可以看看Nvidia后来出的GauGAN，也是类似的应用场景，不过模型本身应该更好。
https://blogs.nvidia.com/blog/2019/03/18/gaugan-photorealistic-landscapes-nvidia-research/

**Comment by Chungegeya** [comment]
好的，谢谢fing神的解答，HED生成出来的应该是黑色的底白色的线，但是看论文是白色的底黑色的线，这个是反二值化操作嘛？

**Comment by imfing** [comment]
如果是黑底的话应该挺好转换的，反向一下就行

**Comment by Chungegeya** [comment]
好的谢谢！
